version: '3'
services:
  webapi:
    build: ./
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=Root123
      - DB_NAME=Animals
      - ROUND_COUNT=8
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: on-failure
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Animals
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    restart: always
  tests:
      image: mrexpen/planet_olymp_phase2
      pull_policy: always
      ports:
        - "8090:8080"
      depends_on:
        - webapi
      environment:
        SERVER_URL: http://webapi:5000
        STAGE: all
