// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnimalsColumns holds the columns for the "animals" table.
	AnimalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "weight", Type: field.TypeFloat32},
		{Name: "length", Type: field.TypeFloat32},
		{Name: "height", Type: field.TypeFloat32},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"MALE", "FEMALE", "OTHER"}},
		{Name: "life_status", Type: field.TypeEnum, Enums: []string{"ALIVE", "DEAD"}, Default: "ALIVE"},
		{Name: "chipping_date_time", Type: field.TypeTime},
		{Name: "death_date_time", Type: field.TypeTime, Nullable: true},
		{Name: "chipping_location_id", Type: field.TypeUint64, Nullable: true},
		{Name: "chipper_id", Type: field.TypeUint32, Nullable: true},
	}
	// AnimalsTable holds the schema information for the "animals" table.
	AnimalsTable = &schema.Table{
		Name:       "animals",
		Columns:    AnimalsColumns,
		PrimaryKey: []*schema.Column{AnimalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "animals_locations_chipped_animals",
				Columns:    []*schema.Column{AnimalsColumns[8]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "animals_users_animals",
				Columns:    []*schema.Column{AnimalsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AnimalTagsColumns holds the columns for the "animal_tags" table.
	AnimalTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "type", Type: field.TypeString, Unique: true},
	}
	// AnimalTagsTable holds the schema information for the "animal_tags" table.
	AnimalTagsTable = &schema.Table{
		Name:       "animal_tags",
		Columns:    AnimalTagsColumns,
		PrimaryKey: []*schema.Column{AnimalTagsColumns[0]},
	}
	// AnimalTypesColumns holds the columns for the "animal_types" table.
	AnimalTypesColumns = []*schema.Column{
		{Name: "animal_id", Type: field.TypeUint64},
		{Name: "type_id", Type: field.TypeUint64},
	}
	// AnimalTypesTable holds the schema information for the "animal_types" table.
	AnimalTypesTable = &schema.Table{
		Name:       "animal_types",
		Columns:    AnimalTypesColumns,
		PrimaryKey: []*schema.Column{AnimalTypesColumns[0], AnimalTypesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "animal_types_animals_animals",
				Columns:    []*schema.Column{AnimalTypesColumns[0]},
				RefColumns: []*schema.Column{AnimalsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "animal_types_animal_tags_types",
				Columns:    []*schema.Column{AnimalTypesColumns[1]},
				RefColumns: []*schema.Column{AnimalTagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AreasColumns holds the columns for the "areas" table.
	AreasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// AreasTable holds the schema information for the "areas" table.
	AreasTable = &schema.Table{
		Name:       "areas",
		Columns:    AreasColumns,
		PrimaryKey: []*schema.Column{AreasColumns[0]},
	}
	// LocationsColumns holds the columns for the "locations" table.
	LocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
	}
	// LocationsTable holds the schema information for the "locations" table.
	LocationsTable = &schema.Table{
		Name:       "locations",
		Columns:    LocationsColumns,
		PrimaryKey: []*schema.Column{LocationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "location_latitude_longitude",
				Unique:  true,
				Columns: []*schema.Column{LocationsColumns[1], LocationsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"USER", "CHIPPER", "ADMIN"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VisitedLocationsColumns holds the columns for the "visited_locations" table.
	VisitedLocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "date_time_of_visit_location_point", Type: field.TypeTime, Nullable: true},
		{Name: "animal_id", Type: field.TypeUint64},
		{Name: "location_id", Type: field.TypeUint64},
	}
	// VisitedLocationsTable holds the schema information for the "visited_locations" table.
	VisitedLocationsTable = &schema.Table{
		Name:       "visited_locations",
		Columns:    VisitedLocationsColumns,
		PrimaryKey: []*schema.Column{VisitedLocationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "visited_locations_animals_animals",
				Columns:    []*schema.Column{VisitedLocationsColumns[2]},
				RefColumns: []*schema.Column{AnimalsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "visited_locations_locations_locations",
				Columns:    []*schema.Column{VisitedLocationsColumns[3]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "visitedlocation_animal_id_location_id",
				Unique:  true,
				Columns: []*schema.Column{VisitedLocationsColumns[2], VisitedLocationsColumns[3]},
			},
		},
	}
	// AreaPointsColumns holds the columns for the "area_points" table.
	AreaPointsColumns = []*schema.Column{
		{Name: "area_id", Type: field.TypeUint64},
		{Name: "location_id", Type: field.TypeUint64},
	}
	// AreaPointsTable holds the schema information for the "area_points" table.
	AreaPointsTable = &schema.Table{
		Name:       "area_points",
		Columns:    AreaPointsColumns,
		PrimaryKey: []*schema.Column{AreaPointsColumns[0], AreaPointsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "area_points_area_id",
				Columns:    []*schema.Column{AreaPointsColumns[0]},
				RefColumns: []*schema.Column{AreasColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "area_points_location_id",
				Columns:    []*schema.Column{AreaPointsColumns[1]},
				RefColumns: []*schema.Column{LocationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnimalsTable,
		AnimalTagsTable,
		AnimalTypesTable,
		AreasTable,
		LocationsTable,
		UsersTable,
		VisitedLocationsTable,
		AreaPointsTable,
	}
)

func init() {
	AnimalsTable.ForeignKeys[0].RefTable = LocationsTable
	AnimalsTable.ForeignKeys[1].RefTable = UsersTable
	AnimalTypesTable.ForeignKeys[0].RefTable = AnimalsTable
	AnimalTypesTable.ForeignKeys[1].RefTable = AnimalTagsTable
	VisitedLocationsTable.ForeignKeys[0].RefTable = AnimalsTable
	VisitedLocationsTable.ForeignKeys[1].RefTable = LocationsTable
	AreaPointsTable.ForeignKeys[0].RefTable = AreasTable
	AreaPointsTable.ForeignKeys[1].RefTable = LocationsTable
}
