// Code generated by ent, DO NOT EDIT.

package ent

import (
	"animals/ent/animaltag"
	"animals/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimalTagDelete is the builder for deleting a AnimalTag entity.
type AnimalTagDelete struct {
	config
	hooks    []Hook
	mutation *AnimalTagMutation
}

// Where appends a list predicates to the AnimalTagDelete builder.
func (atd *AnimalTagDelete) Where(ps ...predicate.AnimalTag) *AnimalTagDelete {
	atd.mutation.Where(ps...)
	return atd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (atd *AnimalTagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AnimalTagMutation](ctx, atd.sqlExec, atd.mutation, atd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (atd *AnimalTagDelete) ExecX(ctx context.Context) int {
	n, err := atd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (atd *AnimalTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(animaltag.Table, sqlgraph.NewFieldSpec(animaltag.FieldID, field.TypeUint64))
	if ps := atd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, atd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	atd.mutation.done = true
	return affected, err
}

// AnimalTagDeleteOne is the builder for deleting a single AnimalTag entity.
type AnimalTagDeleteOne struct {
	atd *AnimalTagDelete
}

// Where appends a list predicates to the AnimalTagDelete builder.
func (atdo *AnimalTagDeleteOne) Where(ps ...predicate.AnimalTag) *AnimalTagDeleteOne {
	atdo.atd.mutation.Where(ps...)
	return atdo
}

// Exec executes the deletion query.
func (atdo *AnimalTagDeleteOne) Exec(ctx context.Context) error {
	n, err := atdo.atd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{animaltag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (atdo *AnimalTagDeleteOne) ExecX(ctx context.Context) {
	if err := atdo.Exec(ctx); err != nil {
		panic(err)
	}
}
