// Code generated by ent, DO NOT EDIT.

package ent

import (
	"animals/ent/animaltype"
	"animals/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimalTypeDelete is the builder for deleting a AnimalType entity.
type AnimalTypeDelete struct {
	config
	hooks    []Hook
	mutation *AnimalTypeMutation
}

// Where appends a list predicates to the AnimalTypeDelete builder.
func (atd *AnimalTypeDelete) Where(ps ...predicate.AnimalType) *AnimalTypeDelete {
	atd.mutation.Where(ps...)
	return atd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (atd *AnimalTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AnimalTypeMutation](ctx, atd.sqlExec, atd.mutation, atd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (atd *AnimalTypeDelete) ExecX(ctx context.Context) int {
	n, err := atd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (atd *AnimalTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(animaltype.Table, sqlgraph.NewFieldSpec(animaltype.FieldID, field.TypeInt64))
	if ps := atd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, atd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	atd.mutation.done = true
	return affected, err
}

// AnimalTypeDeleteOne is the builder for deleting a single AnimalType entity.
type AnimalTypeDeleteOne struct {
	atd *AnimalTypeDelete
}

// Where appends a list predicates to the AnimalTypeDelete builder.
func (atdo *AnimalTypeDeleteOne) Where(ps ...predicate.AnimalType) *AnimalTypeDeleteOne {
	atdo.atd.mutation.Where(ps...)
	return atdo
}

// Exec executes the deletion query.
func (atdo *AnimalTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := atdo.atd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{animaltype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (atdo *AnimalTypeDeleteOne) ExecX(ctx context.Context) {
	if err := atdo.Exec(ctx); err != nil {
		panic(err)
	}
}
