// Code generated by ent, DO NOT EDIT.

package ent

import (
	"animals/ent/animal"
	"animals/ent/location"
	"animals/ent/predicate"
	"animals/ent/visitedlocation"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VisitedLocationQuery is the builder for querying VisitedLocation entities.
type VisitedLocationQuery struct {
	config
	ctx           *QueryContext
	order         []OrderFunc
	inters        []Interceptor
	predicates    []predicate.VisitedLocation
	withAnimals   *AnimalQuery
	withLocations *LocationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VisitedLocationQuery builder.
func (vlq *VisitedLocationQuery) Where(ps ...predicate.VisitedLocation) *VisitedLocationQuery {
	vlq.predicates = append(vlq.predicates, ps...)
	return vlq
}

// Limit the number of records to be returned by this query.
func (vlq *VisitedLocationQuery) Limit(limit int) *VisitedLocationQuery {
	vlq.ctx.Limit = &limit
	return vlq
}

// Offset to start from.
func (vlq *VisitedLocationQuery) Offset(offset int) *VisitedLocationQuery {
	vlq.ctx.Offset = &offset
	return vlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vlq *VisitedLocationQuery) Unique(unique bool) *VisitedLocationQuery {
	vlq.ctx.Unique = &unique
	return vlq
}

// Order specifies how the records should be ordered.
func (vlq *VisitedLocationQuery) Order(o ...OrderFunc) *VisitedLocationQuery {
	vlq.order = append(vlq.order, o...)
	return vlq
}

// QueryAnimals chains the current query on the "animals" edge.
func (vlq *VisitedLocationQuery) QueryAnimals() *AnimalQuery {
	query := (&AnimalClient{config: vlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(visitedlocation.Table, visitedlocation.FieldID, selector),
			sqlgraph.To(animal.Table, animal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, visitedlocation.AnimalsTable, visitedlocation.AnimalsColumn),
		)
		fromU = sqlgraph.SetNeighbors(vlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocations chains the current query on the "locations" edge.
func (vlq *VisitedLocationQuery) QueryLocations() *LocationQuery {
	query := (&LocationClient{config: vlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(visitedlocation.Table, visitedlocation.FieldID, selector),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, visitedlocation.LocationsTable, visitedlocation.LocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(vlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VisitedLocation entity from the query.
// Returns a *NotFoundError when no VisitedLocation was found.
func (vlq *VisitedLocationQuery) First(ctx context.Context) (*VisitedLocation, error) {
	nodes, err := vlq.Limit(1).All(setContextOp(ctx, vlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{visitedlocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vlq *VisitedLocationQuery) FirstX(ctx context.Context) *VisitedLocation {
	node, err := vlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VisitedLocation ID from the query.
// Returns a *NotFoundError when no VisitedLocation ID was found.
func (vlq *VisitedLocationQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = vlq.Limit(1).IDs(setContextOp(ctx, vlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{visitedlocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vlq *VisitedLocationQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := vlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VisitedLocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VisitedLocation entity is found.
// Returns a *NotFoundError when no VisitedLocation entities are found.
func (vlq *VisitedLocationQuery) Only(ctx context.Context) (*VisitedLocation, error) {
	nodes, err := vlq.Limit(2).All(setContextOp(ctx, vlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{visitedlocation.Label}
	default:
		return nil, &NotSingularError{visitedlocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vlq *VisitedLocationQuery) OnlyX(ctx context.Context) *VisitedLocation {
	node, err := vlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VisitedLocation ID in the query.
// Returns a *NotSingularError when more than one VisitedLocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (vlq *VisitedLocationQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = vlq.Limit(2).IDs(setContextOp(ctx, vlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{visitedlocation.Label}
	default:
		err = &NotSingularError{visitedlocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vlq *VisitedLocationQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := vlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VisitedLocations.
func (vlq *VisitedLocationQuery) All(ctx context.Context) ([]*VisitedLocation, error) {
	ctx = setContextOp(ctx, vlq.ctx, "All")
	if err := vlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VisitedLocation, *VisitedLocationQuery]()
	return withInterceptors[[]*VisitedLocation](ctx, vlq, qr, vlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vlq *VisitedLocationQuery) AllX(ctx context.Context) []*VisitedLocation {
	nodes, err := vlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VisitedLocation IDs.
func (vlq *VisitedLocationQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if vlq.ctx.Unique == nil && vlq.path != nil {
		vlq.Unique(true)
	}
	ctx = setContextOp(ctx, vlq.ctx, "IDs")
	if err = vlq.Select(visitedlocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vlq *VisitedLocationQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := vlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vlq *VisitedLocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vlq.ctx, "Count")
	if err := vlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vlq, querierCount[*VisitedLocationQuery](), vlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vlq *VisitedLocationQuery) CountX(ctx context.Context) int {
	count, err := vlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vlq *VisitedLocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vlq.ctx, "Exist")
	switch _, err := vlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vlq *VisitedLocationQuery) ExistX(ctx context.Context) bool {
	exist, err := vlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VisitedLocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vlq *VisitedLocationQuery) Clone() *VisitedLocationQuery {
	if vlq == nil {
		return nil
	}
	return &VisitedLocationQuery{
		config:        vlq.config,
		ctx:           vlq.ctx.Clone(),
		order:         append([]OrderFunc{}, vlq.order...),
		inters:        append([]Interceptor{}, vlq.inters...),
		predicates:    append([]predicate.VisitedLocation{}, vlq.predicates...),
		withAnimals:   vlq.withAnimals.Clone(),
		withLocations: vlq.withLocations.Clone(),
		// clone intermediate query.
		sql:  vlq.sql.Clone(),
		path: vlq.path,
	}
}

// WithAnimals tells the query-builder to eager-load the nodes that are connected to
// the "animals" edge. The optional arguments are used to configure the query builder of the edge.
func (vlq *VisitedLocationQuery) WithAnimals(opts ...func(*AnimalQuery)) *VisitedLocationQuery {
	query := (&AnimalClient{config: vlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vlq.withAnimals = query
	return vlq
}

// WithLocations tells the query-builder to eager-load the nodes that are connected to
// the "locations" edge. The optional arguments are used to configure the query builder of the edge.
func (vlq *VisitedLocationQuery) WithLocations(opts ...func(*LocationQuery)) *VisitedLocationQuery {
	query := (&LocationClient{config: vlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vlq.withLocations = query
	return vlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AnimalID uint64 `json:"animal_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VisitedLocation.Query().
//		GroupBy(visitedlocation.FieldAnimalID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vlq *VisitedLocationQuery) GroupBy(field string, fields ...string) *VisitedLocationGroupBy {
	vlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VisitedLocationGroupBy{build: vlq}
	grbuild.flds = &vlq.ctx.Fields
	grbuild.label = visitedlocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AnimalID uint64 `json:"animal_id,omitempty"`
//	}
//
//	client.VisitedLocation.Query().
//		Select(visitedlocation.FieldAnimalID).
//		Scan(ctx, &v)
func (vlq *VisitedLocationQuery) Select(fields ...string) *VisitedLocationSelect {
	vlq.ctx.Fields = append(vlq.ctx.Fields, fields...)
	sbuild := &VisitedLocationSelect{VisitedLocationQuery: vlq}
	sbuild.label = visitedlocation.Label
	sbuild.flds, sbuild.scan = &vlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VisitedLocationSelect configured with the given aggregations.
func (vlq *VisitedLocationQuery) Aggregate(fns ...AggregateFunc) *VisitedLocationSelect {
	return vlq.Select().Aggregate(fns...)
}

func (vlq *VisitedLocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vlq); err != nil {
				return err
			}
		}
	}
	for _, f := range vlq.ctx.Fields {
		if !visitedlocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vlq.path != nil {
		prev, err := vlq.path(ctx)
		if err != nil {
			return err
		}
		vlq.sql = prev
	}
	return nil
}

func (vlq *VisitedLocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VisitedLocation, error) {
	var (
		nodes       = []*VisitedLocation{}
		_spec       = vlq.querySpec()
		loadedTypes = [2]bool{
			vlq.withAnimals != nil,
			vlq.withLocations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VisitedLocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VisitedLocation{config: vlq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vlq.withAnimals; query != nil {
		if err := vlq.loadAnimals(ctx, query, nodes, nil,
			func(n *VisitedLocation, e *Animal) { n.Edges.Animals = e }); err != nil {
			return nil, err
		}
	}
	if query := vlq.withLocations; query != nil {
		if err := vlq.loadLocations(ctx, query, nodes, nil,
			func(n *VisitedLocation, e *Location) { n.Edges.Locations = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vlq *VisitedLocationQuery) loadAnimals(ctx context.Context, query *AnimalQuery, nodes []*VisitedLocation, init func(*VisitedLocation), assign func(*VisitedLocation, *Animal)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*VisitedLocation)
	for i := range nodes {
		fk := nodes[i].AnimalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(animal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "animal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (vlq *VisitedLocationQuery) loadLocations(ctx context.Context, query *LocationQuery, nodes []*VisitedLocation, init func(*VisitedLocation), assign func(*VisitedLocation, *Location)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*VisitedLocation)
	for i := range nodes {
		fk := nodes[i].LocationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(location.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "location_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vlq *VisitedLocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vlq.querySpec()
	_spec.Node.Columns = vlq.ctx.Fields
	if len(vlq.ctx.Fields) > 0 {
		_spec.Unique = vlq.ctx.Unique != nil && *vlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vlq.driver, _spec)
}

func (vlq *VisitedLocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(visitedlocation.Table, visitedlocation.Columns, sqlgraph.NewFieldSpec(visitedlocation.FieldID, field.TypeUint64))
	_spec.From = vlq.sql
	if unique := vlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vlq.path != nil {
		_spec.Unique = true
	}
	if fields := vlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visitedlocation.FieldID)
		for i := range fields {
			if fields[i] != visitedlocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vlq *VisitedLocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vlq.driver.Dialect())
	t1 := builder.Table(visitedlocation.Table)
	columns := vlq.ctx.Fields
	if len(columns) == 0 {
		columns = visitedlocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vlq.sql != nil {
		selector = vlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vlq.ctx.Unique != nil && *vlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vlq.predicates {
		p(selector)
	}
	for _, p := range vlq.order {
		p(selector)
	}
	if offset := vlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VisitedLocationGroupBy is the group-by builder for VisitedLocation entities.
type VisitedLocationGroupBy struct {
	selector
	build *VisitedLocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vlgb *VisitedLocationGroupBy) Aggregate(fns ...AggregateFunc) *VisitedLocationGroupBy {
	vlgb.fns = append(vlgb.fns, fns...)
	return vlgb
}

// Scan applies the selector query and scans the result into the given value.
func (vlgb *VisitedLocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vlgb.build.ctx, "GroupBy")
	if err := vlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitedLocationQuery, *VisitedLocationGroupBy](ctx, vlgb.build, vlgb, vlgb.build.inters, v)
}

func (vlgb *VisitedLocationGroupBy) sqlScan(ctx context.Context, root *VisitedLocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vlgb.fns))
	for _, fn := range vlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vlgb.flds)+len(vlgb.fns))
		for _, f := range *vlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VisitedLocationSelect is the builder for selecting fields of VisitedLocation entities.
type VisitedLocationSelect struct {
	*VisitedLocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vls *VisitedLocationSelect) Aggregate(fns ...AggregateFunc) *VisitedLocationSelect {
	vls.fns = append(vls.fns, fns...)
	return vls
}

// Scan applies the selector query and scans the result into the given value.
func (vls *VisitedLocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vls.ctx, "Select")
	if err := vls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitedLocationQuery, *VisitedLocationSelect](ctx, vls.VisitedLocationQuery, vls, vls.inters, v)
}

func (vls *VisitedLocationSelect) sqlScan(ctx context.Context, root *VisitedLocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vls.fns))
	for _, fn := range vls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
