// Code generated by ent, DO NOT EDIT.

package animal

const (
	// Label holds the string label denoting the animal type in the database.
	Label = "animal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the animal in the database.
	Table = "animals"
)

// Columns holds all SQL columns for animal fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
